FROM php:8.1-cli AS builder

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    curl \
    nodejs \
    npm \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    && docker-php-ext-install pdo pdo_mysql zip exif \
    && rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

RUN git clone https://github.com/Prajwal100/Complete-Ecommerce-in-laravel-10.git .

RUN cp .env.example .env

RUN composer install --no-dev --optimize-autoloader

RUN npm install && npm run

# FROM php:8.1-fpm AS runtime

# RUN apt-get update && apt-get install -y \
#     libpng-dev \
#     libjpeg-dev \
#     libfreetype6-dev \
#     libzip-dev \
#     && docker-php-ext-install pdo pdo_mysql zip exif \
#     && rm -rf /var/lib/apt/lists/*
# COPY --from=builder /app /app

FROM nginx:alpine

COPY --from=builder /app /usr/share/nginx/html

EXPOSE 8000
