FROM ubuntu:22.04 AS builder
# RUN apt install git \
RUN apt-get update && apt-get install -y git \
    && git clone https://github.com/Prajwal100/Complete-Ecommerce-in-laravel-10.git \
    && cp Complete-Ecommerce-in-laravel-10/.env.example Complete-Ecommerce-in-laravel-10/.env

FROM php:8.1
COPY --from=builder /Complete-Ecommerce-in-laravel-10 /Complete-Ecommerce-in-laravel-10
RUN apt update && apt install -y nodejs npm bash
RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin \
    --filename=composer
RUN docker-php-ext-install exif pdo pdo_mysql mysqli
WORKDIR /Complete-Ecommerce-in-laravel-10
RUN composer update && composer install
RUN npm install 
RUN php artisan key:generate \
    && php artisan migrate --seed \
    && php artisan storage:link \
    # && chown -R nginx:nginx /usr/share/nginx/html/storage /usr/share/nginx/html/bootstrap/cache \
    && artisan serve --host=localhost --port=80 ;
EXPOSE 80